id: P456C49B4
initial_creation_type: ocr
source_metadata:
  volumes:
    22348b892b0146bab2c32c04a938284e:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་སྒོ་དྲུག་པའི་གཟུངས་ཀྱི་རྣམ་པར་བཤད་པ།
      total_pages: 1379
      volume_number: 37
